### ISSUE TITLE
Example on Docker hub page doesn't work

### ISSUE THREAD

**Issue by synaptiko** [Budry/docker-cz-nic-hass#1]
When running
```
$ docker run \
 -d \ 
 -e DEVICE_TOKEN=<MY_TOKEN> \
 -v ./haas.log:/var/log/haas.log \
 budry/docker-cz-nic-haas
```

I got `docker: Error response from daemon: create ./haas.log: "./haas.log" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.`

When changed to the absolute path
```
$ docker run \
 -d \ 
 -e DEVICE_TOKEN=<MY_TOKEN> \
 -v /home/<my-user>/logs/haas.log:/var/log/haas.log \
 budry/docker-cz-nic-haas
```

the container is stopped immediately and I see this in docker logs:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/haas_proxy/__main__.py", line 12, in <module>
    run()
  File "/usr/local/lib/python3.6/site-packages/twisted/scripts/twistd.py", line 29, in run
    app.run(runApp, ServerOptions)
  File "/usr/local/lib/python3.6/site-packages/twisted/application/app.py", line 662, in run
    runApp(config)
  File "/usr/local/lib/python3.6/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/local/lib/python3.6/site-packages/twisted/application/app.py", line 382, in run
    self.logger.start(self.application)
  File "/usr/local/lib/python3.6/site-packages/twisted/application/app.py", line 191, in start
    observer = self._getLogObserver()
  File "/usr/local/lib/python3.6/site-packages/twisted/scripts/_twistd_unix.py", line 160, in _getLogObserver
    logFile = logfile.LogFile.fromFullPath(self._logfilename)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/logfile.py", line 54, in fromFullPath
    os.path.dirname(logPath), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/logfile.py", line 170, in __init__
    BaseLogFile.__init__(self, name, directory, defaultMode)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/logfile.py", line 45, in __init__
    self._openFile()
  File "/usr/local/lib/python3.6/site-packages/twisted/python/logfile.py", line 175, in _openFile
    BaseLogFile._openFile(self)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/logfile.py", line 74, in _openFile
    self._file = open(self.path, "rb+", 0)
IsADirectoryError: [Errno 21] Is a directory: '/var/log/haas.log'
```

I had to change it like this, then it worked:
```
$ docker run \
 -d \ 
 -e DEVICE_TOKEN=<MY_TOKEN> \
 -v /home/<my-user>/logs:/var/log \
 budry/docker-cz-nic-haas
```

**Comment by Budry** [comment]
Hi, thanks! You have right. Volume must be absolute path to parent directory. I'm sorry  I copy volume entry from `docker-compose` file that can contains relative paths...
